### ISSUE TITLE
npm install deasync fails

### ISSUE THREAD

**Issue by ForiDunk** [abbr/deasync#106]
After runing `npm install deasync` the following problem occurred:

**...
verbose node v11.1.0
verbose npm  v6.4.1
error code ELIFECYCLE
error errno 1
error deasync@0.1.13 install: `node ./build.js`
error Exit status 1
error Failed at the deasync@0.1.13 install script.
error This is probably not a problem with npm. There is likely additional logging output above.
verbose exit [ 1, true ]**

Any suggestions how can I install deasync? without it I cannot use `parcel-bundler`

**Comment by MrFlutters** [comment]
I'm currently using 
>"deasync": "0.1.13"
>"parcel-bundler": "1.10.3"

I have no issues using parcel-bundler on windows and Docker node:11.1.0

**However**, Using Docker node:11.1.0-alpine causes an error simular to this, due to missing python depencendy of node-gyp required for deasync.

These may be simular, depending on your setup, as its hard to tell with your error log

```
> deasync@0.1.13 install /usr/src/app/node_modules/deasync
> node ./build.js

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:161:21)
gyp ERR! System Linux 4.14.79-boot2docker
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/src/app/node_modules/deasync
gyp ERR! node -v v11.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.13 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-13T14_52_30_225Z-debug.log
```

**Comment by abbr** [comment]
Just published v0.1.14 which comes with pre-compiled binaries for node v11 and should fix your problem.

**Comment by Parthian** [comment]
Hi Abbr,

I'm seeing much the same but with deasync 0.1.15 and node v13.1.0.

I assume missing binaries from here https://github.com/abbr/deasync-bin so for Win10 everyone needs a  win32-x64-node-13 	for node 13 win64  binary folder?

And then all the problems with nody-gyp trying to build deasync and failing to find Python will go away (why node-gyp can't find Python appears to be another story).

I came across this issue using Parcel-Bundler. I wonder if they really need deasync? Especially as it seems to be a workaround for legacy issues? And what is odd that Node 13 has been out for a month or so, so not sure why no one else has come across this...

Cheers - Parthian

**Comment by MrFlutters** [comment]
@Parthian Yes, because the binary is missing, npm will attempt to build it.

npm uses node-gyp, that requires python to build. You usually will get this when you try and use newer node versions. (no node v13 builds for deasync are currently prebuilt), 

node-gyp is only required when it cannot download a prebuilt binary.

If node-gyp cannot find python, then make sure that python is a valid command (python2/python3) wont work.

The use of Parcel-Bundler with deasync would be something you need bring up with Parcel-Bundler, not here.

**Comment by Parthian** [comment]
Yep, typing Python at cmd prompt results in a Python37 error - C:\Users\USERNAME\AppData\Local\Programs\Python\Python37\\lib\site.py. The double slash is odd too, but I think this is due to my use of Django and some error there. I normally run Python3 but that is opening up a Microsoft store... asking me to download Python. So I've a problem there too.

Tried set PYTHON=C:\Python27\python.exe which was recommended as a temporary workaround for this problem. Didn't help.

> no node v13 builds for deasync are currently prebuilt

Maybe that would be handy for everyone? 
But abandoning Parcel for now, maybe when Parcel2 is out I'll look into it again.

**Comment by abbr** [comment]
Fixed with deasync@0.1.16

**Comment by t3hmrman** [comment]
For those using `yarn` you can force the resolution of `0.1.16` (for a dependency like `parcel-bundler`) with the following JSON in `package.json`:

```json
"resolutions": {
  "deasync": "0.1.16"
}
```

**Comment by JLarky** [comment]
I'm leaving this here just because maybe google will send you here as it sent me 🤪

updating xcode after macos update fixed this for me:

```bash
xcode-select --install
```

error:
```
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ] 
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools),
missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun    
```

[source](https://twitter.com/JLarky/status/1596318478369071105)

**Comment by Nevin1901** [comment]
If anyone is coming across this and have updated their xcode tools but it still fails, run

`npm install -g node-gyp`

That fixed the issue for me on m2 mac.

**Comment by Connerk1** [comment]
In case this helps anyone in the future. On Mac m1 using homebrew for python.

You can use `npm config get python` to check which Python version npm will use for its operations.
If you get undefined you will need to set python to your path `npm config set python python3.8`.

For me, downgrading to v3.8 seemed to resolve my npm install issues. Originally deasync was trying to use my default version of 3.11 during the build script.

**Comment by xanthuz** [comment]
> npm config set python



> In case this helps anyone in the future. On Mac m1 using homebrew for python.
> 
> You can use `npm config get python` to check which Python version npm will use for its operations. If you get undefined you will need to set python to your path `npm config set python python3.8`.
> 
> For me, downgrading to v3.8 seemed to resolve my npm install issues. Originally deasync was trying to use my default version of 3.11 during the build script.

It works for me.
I installed python3.8.10, delete folder `/node_modules`, and run `yarn cache clean`.
Then, run `yarn` to reinstall.
Project build success! Thanks!
