### ISSUE TITLE
C lib error while dealing with a huge number of calls

### ISSUE THREAD

**Issue by fmsouza** [abbr/deasync#24]
I'm using this module in my application to synchronize some calls to mongodb routines, and while I'm testing the application with a HTTP request robot requesting each 100ms, near 50 times (in around 3hr) there was accused an error in the console.

```node: ../deps/uv/src/unix/async.c:158: uv__async_io: Assertion `n == sizeof(val)' failed.```

And it always appears lots of times in a row.

**Comment by fmsouza** [comment]
I just added another robot requesting every 20ms and the server was gone forever.

**Comment by abbr** [comment]
How do you know the error is caused by deasync?

**Comment by fmsouza** [comment]
This is the only module I use that uses C libs and uses it do deal with my async context.

In my stack, there is ExpressJS dealing with HTTP requests, a Database driver which abstracts the connection to MongoDB and using ```deasync``` to remove the callbacks.

**Comment by abbr** [comment]
Node is written in C++ so every module, including built-in ones depend on c libs directly or indirectly. Besides, the error message has no indication on deasync. Your argument is unjustified. I'll close the ticket unless you:
1. can confirm by removing/replacing deasync and deasync alone, the problem is gone; and
2. post your code and test method/script in a self-contained, reproducible way.
