### ISSUE TITLE
Could not locate the bindings file

### ISSUE THREAD

**Issue by Aarilight** [abbr/deasync#26]
Uncaught Error: Could not locate the bindings file. Tried:
     → deasync\build\deasync.node
     → deasync\build\Debug\deasync.node
     → deasync\build\Release\deasync.node
     → deasync\out\Debug\deasync.node
     → deasync\Debug\deasync.node
     → deasync\out\Release\deasync.node
     → deasync\Release\deasync.node
     → deasync\build\default\deasync.node
     → deasync\compiled\2.3.1\win32\x64\deasync.node

I saw the previous issue that had the same error, and tried the solution (uninstalling and reinstalling) but it didn't seem to do anything (which makes sense because this is from a fresh install anyway).

I tried to do a bit of debugging myself, and none of the paths it tried existed. When it installs, it says the binary is fine but doesn't make any of those paths. Is it supposed to? I tried putting the compiled files into one of the folders (I tried the first one and the last one), but then bindings.js complained about it not self-registering.

Am I doing something wrong, or...?

**Comment by abbr** [comment]
I suspect you switched node to iojs using something like nvm, or changed node/iojs versions since last installing deasync. Every time you do this, you have to wipe out node_modules and re-run `npm install` in order to re-compile all modules written in C++ including deasync, of which compilation may depend on node/iojs version. You also need to verify the prerequisites documented in readme are met, such as c++ compilers, python, and node-gyp are installed.

**Comment by Aarilight** [comment]
Actually, it might be the prerequisites thing. Last time I tried to use deasync it worked fine, but when I installed it then I had all of those installed. Since then I've had a fresh install of windows (8.1) so they might not be installed yet. 
I do know that my node version hasn't changed since I generated the node_modules folder tho
